version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.2
      

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt
            python3 manage.py makemigrations
            python3 manage.py migrate

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}
        
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            python manage.py test

      - store_artifacts:
          path: test-reports
          destination: test-reports
          
  deploy:
    machine:
        enabled: true
    steps:
      - checkout
      - run:
          name: Deploy Dev to Heroku
          command: |
            git push https://heroku:2b2b0ebd-2523-451f-bac7-2d53f34e0a50@git.heroku.com/tbl-circle.git master

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: dev
